platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
      
      # Workaround for BoringSSL-GRPC build issue on ARM64 macOS
      # The -G flag causes "clang: error: unsupported option '-G'" on ARM64
      if target.name == 'BoringSSL-GRPC'
        # Remove all warning-related flags
        config.build_settings.delete('GCC_WARN_INHIBIT_ALL_WARNINGS')
        config.build_settings['WARNING_CFLAGS'] = '-Wno-everything'
        
        # Remove -G from all flag settings
        ['OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |key|
          flags = config.build_settings[key]
          if flags.is_a?(String)
            config.build_settings[key] = flags.gsub(/\s-G\s/, ' ').gsub(/^-G\s/, '').gsub(/\s-G$/, '')
          elsif flags.is_a?(Array)
            config.build_settings[key] = flags.reject { |flag| flag == '-G' }
          end
        end
      end
    end
  end
  
  # Additional fix: Modify the Pods project file directly to remove -G
  project_path = File.join(installer.pods_project.path, 'project.pbxproj')
  if File.exist?(project_path)
    project_content = File.read(project_path)
    if project_content.include?(' -G ')
      project_content.gsub!(/ -G /, ' ')
      File.write(project_path, project_content)
      puts "Removed -G flag from Pods project file"
    end
  end
end
